---
- name: Clone repo branch
  git:
    repo: '{{ nimbus_fluffy_repo_url }}'
    version: '{{ nimbus_fluffy_repo_branch }}'
    dest: '{{ nimbus_fluffy_repo_path }}'
    force: true
    update: true
  become_user: '{{ nimbus_fluffy_user }}'

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ nimbus_fluffy_build_script_path }}'
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
    mode: 0775

- name: Check if node binary exists
  stat:
    path: '{{ nimbus_fluffy_binary_path }}'
  register: nimbus_fluffy_bin

- name: Create timer for build script
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: '{{ nimbus_fluffy_build_service_name }}'
    systemd_timer_user: '{{ nimbus_fluffy_user }}'
    systemd_timer_group: '{{ nimbus_fluffy_group }}'
    systemd_timer_description: 'Build {{ nimbus_fluffy_service_name }}'
    systemd_timer_start_on_creation: '{{ not nimbus_fluffy_bin.stat.exists }}'
    systemd_timer_ionice_class: 'idle'
    systemd_timer_consul_warning: true
    systemd_timer_enabled: '{{ nimbus_fluffy_build_timer_enabled }}'
    systemd_timer_frequency: '{{ nimbus_fluffy_build_frequency }}'
    systemd_timer_timeout_sec: '{{ nimbus_fluffy_build_timer_timeout }}'
    systemd_timer_work_dir: '{{ nimbus_fluffy_service_path }}'
    systemd_timer_script_path: '{{ nimbus_fluffy_build_script_path }}'
