---
- name: Create service directory
  file:
    path: '{{ nimbus_fluffy_data_path }}'
    state: directory
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
    mode: 0770

- name: Create netkey file (optional)
  copy:
    dest: '{{ nimbus_fluffy_netkey_path }}'
    content: '{{ nimbus_fluffy_netkey }}'
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
    mode: 0600
  when: nimbus_fluffy_netkey is defined

- name: Create bootstrap node file
  copy:
    dest: '{{ nimbus_fluffy_bootstrap_path }}'
    content: '{{ nimbus_fluffy_bootstrap_nodes | join("\n") }}'
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
    mode: 0600
  when: nimbus_fluffy_bootstrap_nodes|length > 0

- name: Create JSON RPC wrapper script
  template:
    src: 'rpc.sh.j2'
    dest: '{{ nimbus_fluffy_rpc_script_path }}'
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
    mode: 0750

- name: Create Ansible toggle script
  copy:
    src: 'ansible_toggle.sh'
    dest: '{{ nimbus_fluffy_service_path }}/ansible_enabled.sh'
    mode: 0750
    owner: '{{ nimbus_fluffy_user }}'
    group: '{{ nimbus_fluffy_group }}'
