---
- name: 'Create Consul service definition'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ nimbus_fluffy_consul_service_file_name }}'
    consul_services:
      - id: '{{ nimbus_fluffy_service_name }}'
        name: '{{ nimbus_fluffy_consul_service_name }}'
        port: '{{ nimbus_fluffy_listening_port }}'
        address: '{{ nimbus_fluffy_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'eth1', 'nimbus']
        #checks:
        #  - name: '{{ nimbus_fluffy_consul_service_name }}-test-health'
        #    type: 'http'
        #    http: 'http://localhost:{{ nimbus_fluffy_rest_port }}/eth/v1/node/version'

      - id: '{{ nimbus_fluffy_service_name }}-metrics'
        name: '{{ nimbus_fluffy_consul_metrics_service_name }}'
        port: '{{ nimbus_fluffy_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'eth1', 'nimbus', 'metrics']
        meta:
          container: '{{ nimbus_fluffy_service_name }}'
        checks:
          - name: '{{ nimbus_fluffy_consul_metrics_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ nimbus_fluffy_metrics_port }}/health'
