---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_fluffy_service_name }}'
    dest: '{{ nimbus_fluffy_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'fluffy.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_fluffy_service_name }}.service'
    mode: 0644
  register: nimbus_fluffy_service_definition

- name: Reload and restart the service
  systemd:
    name: '{{ nimbus_fluffy_service_name }}.service'
    enabled: true
    daemon_reload: true
    state: |-
      {{ nimbus_fluffy_service_definition.changed
       | ternary("restarted", "started") }}
